[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "isp-down"
version = "1.0"
description = "ISP down scripts"
requires-python = ">=3.10"

[project.scripts]
isp-down = "root.main:main"
